#ifndef DGMAC_CONF_H_
#define DGMAC_CONF_H_

#define DGMAC_COLMAP_MAX_LEN 4
#define DGMAC_DATA_MAX_LEN 64
#define DGMAC_SLOTFRAME_TIMESLOTS 16
#define DGMAC_MAX_NEIGHBORS (DGMAC_SLOTFRAME_TIMESLOTS - 1)

#define DGMAC_HEARTBEAT_INTERVAL 4000
#define DGMAC_HEARTBEAT_DEVIATION 200
#define DGMAC_HEARTBEAT_TTL 3
#define DGMAC_PACKET_MAX_LEN (PACKETBUF_SIZE)

#endif
