#ifndef GCHMAC_CONF_H_
#define GCHMAC_CONF_H_

#define GCHMAC_COLMAP_MAX_LEN 4
#define GCHMAC_DATA_MAX_LEN 64
#define GCHMAC_SLOTFRAME_TIMESLOTS 16
#define GCHMAC_MAX_NEIGHBORS (GCHMAC_SLOTFRAME_TIMESLOTS - 1)

#define GCHMAC_HEARTBEAT_INTERVAL 4000
#define GCHMAC_HEARTBEAT_DEVIATION 200
#define GCHMAC_HEARTBEAT_TTL 3
#define GCHMAC_PACKET_MAX_LEN (PACKETBUF_SIZE)

#endif
