#ifndef GCHMAC_CONF_H_
#define GCHMAC_CONF_H_

#define LOG_MODULE "GCH-MAC"
#define LOG_LEVEL LOG_LEVEL_INFO

#define GCHMAC_COLMAP_MAX_LEN 4
#define GCHMAC_DATA_MAX_LEN 64
#define GCHMAC_SLOTFRAME_TIMESLOTS 16
#define GCHMAC_MAX_NODES (GCHMAC_SLOTFRAME_TIMESLOTS - 1)

#define GCHMAC_HEARTBEAT_INTERVAL 200
#endif
