#ifndef __PROJECT_CONF_H__
#define __PROJECT_CONF_H__

#define LOG_CONF_LEVEL_MAC                         LOG_LEVEL_DBG
#define TSCH_PACKET_CONF_EB_WITH_SLOTFRAME_AND_LINK	1
#define WITH_SECURITY 0
#define TSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL 0

#endif //__PROJECT_CONF_H__

